development:
  adapter: async

test:
  adapter: test

production:
  adapter: postgresql
  database: <%= ENV['DATABASE_URL'] %>
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: bean_mate_production
